Add null-guards for token balances
XLabs/portal-bridge-ui pull request #519
Opened 2023-11-14 18:40 UTC by MidnightLightning

Fixes #515 

Update the type definition for data coming back from Covalent API endpoints to allow for nulls, and then guard against null values when enumerating NFT data

2023-11-14 20:20 UTC, sebastianscatularo requested changes

2023-11-14 20:20 UTC, sebastianscatularo commented on src/hooks/useGetSourceParsedTokenAccounts.ts
> +  let amount =
please set the variable as const instead of let

```suggestion
  const amount =
```

2023-11-14 20:37 UTC, M-Picco commented on src/hooks/useGetSourceParsedTokenAccounts.ts
> +    nft_data.token_balance == null
I'd suggest going for `nft_data.token_balance ? formatUnits(nft_data.token_balance, covalent.contract_decimals) : "0"` to cover against any falsy value (e.g. `null`, `undefined`, `''`)

2023-11-14 20:37 UTC, M-Picco commented on src/hooks/useGetSourceParsedTokenAccounts.ts
> +    amount: nft_data.token_balance == null ? "" : nft_data.token_balance,
Same here: `nft_data.token_balance ? nft_data.token_balance : ""`

2023-11-17 15:47 UTC, sebastianscatularo approved these changes

2023-11-17 16:05 UTC, yuli-ferna approved these changes

2023-11-17 16:30 UTC, merged